### ISSUE TITLE
Add slack integration

### ISSUE THREAD

**Issue by ojaswa1942** [ojaswa1942/go-watch#3]
Fn arg similar to email
Not a dynamic integration but a simple push message on failure in production.

**Comment by feildrixliemdra** [comment]
hi there @ojaswa1942 , I'd like to help you with this enhancement as part of Hacktoberfest :)

**Comment by ojaswa1942** [comment]
@feildrixliemdra great! Assigning the issue to you.

**Comment by feildrixliemdra** [comment]
please kindly check this https://github.com/ojaswa1942/go-watch/pull/4 . thanks
