### ISSUE TITLE
Add `golangci-lint`

### ISSUE THREAD

**Issue by iamrajiv** [ojaswa1942/go-watch#9]
## Description

`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE, and has dozens of linters included.

## References

https://golangci-lint.run/

**Comment by iamrajiv** [comment]
@ojaswa1942 I want to work on this as Hacktoberfest PR.

**Comment by ojaswa1942** [comment]
@iamrajiv Sounds good, might be good to have this as a pre-commit hook. Is that what you have in mind?

**Comment by iamrajiv** [comment]
@ojaswa1942 yeah right. Even we can run this linter locally too in system before pushing the code.

**Comment by ojaswa1942** [comment]
Yes, but that would again require everyone to manually run that step every time before a commit. People (including me) tend to miss out on additional steps. A pre-commit hook or similar alternative (Like an action to verify linting on PR?) would fit it smoothly.

Thanks for opening this feature suggestion @iamrajiv. Assigning this issue to you :)
